# Generated by Django 3.1.5 on 2021-01-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210130_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(default='default.png', upload_to='post_videos'),
        ),
    ]
